/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface DepositInterface extends Interface {
  functions: {
    deposit: TypedFunctionDescription<{
      encode([_depositor, _depositRef, _code, _amount]: [
        string,
        Arrayish,
        Arrayish,
        BigNumberish
      ]): string;
    }>;

    withdraw: TypedFunctionDescription<{
      encode([_depositor, _depositRef, _code, _amount]: [
        string,
        Arrayish,
        Arrayish,
        BigNumberish
      ]): string;
    }>;

    setCanWithdraw: TypedFunctionDescription<{
      encode([_depositRef, _canWithdraw]: [Arrayish, boolean]): string;
    }>;
  };

  events: {
    Deposited: TypedEventDescription<{
      encodeTopics([_epochTime, _depositor, _depositRef, _code, _amount]: [
        null,
        null,
        null,
        null,
        null
      ]): string[];
    }>;

    Withdrawn: TypedEventDescription<{
      encodeTopics([_epochTime, _depositor, _depositRef, _code, _amount]: [
        null,
        null,
        null,
        null,
        null
      ]): string[];
    }>;

    CanWithdraw: TypedEventDescription<{
      encodeTopics([_depositRef, _canWithdraw]: [null, null]): string[];
    }>;
  };
}

export class Deposit extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Deposit;
  attach(addressOrName: string): Deposit;
  deployed(): Promise<Deposit>;

  on(event: EventFilter | string, listener: Listener): Deposit;
  once(event: EventFilter | string, listener: Listener): Deposit;
  addListener(eventName: EventFilter | string, listener: Listener): Deposit;
  removeAllListeners(eventName: EventFilter | string): Deposit;
  removeListener(eventName: any, listener: Listener): Deposit;

  interface: DepositInterface;

  functions: {
    getExists(_x: string): Promise<boolean>;

    getDepositor(_index: BigNumberish): Promise<string>;

    getNumDeposits(_depositor: string): Promise<BigNumber>;

    getDepositReference(
      _depositor: string,
      _index: BigNumberish
    ): Promise<string>;

    getDepositedAddress(_depositRef: Arrayish): Promise<string>;

    getDepositedAmount(_depositRef: Arrayish): Promise<BigNumber>;

    getDepositedCode(_depositRef: Arrayish): Promise<string>;

    getCanWithdraw(_depositRef: Arrayish): Promise<boolean>;

    getDeposit(
      _depositRef: Arrayish
    ): Promise<{
      code: string;
      amount: BigNumber;
      account: string;
      canWithdraw: boolean;
    }>;

    deposit(
      _depositor: string,
      _depositRef: Arrayish,
      _code: Arrayish,
      _amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    withdraw(
      _depositor: string,
      _depositRef: Arrayish,
      _code: Arrayish,
      _amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setCanWithdraw(
      _depositRef: Arrayish,
      _canWithdraw: boolean,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getNumDepositors(): Promise<BigNumber>;
  };

  filters: {
    Deposited(
      _epochTime: null,
      _depositor: null,
      _depositRef: null,
      _code: null,
      _amount: null
    ): EventFilter;

    Withdrawn(
      _epochTime: null,
      _depositor: null,
      _depositRef: null,
      _code: null,
      _amount: null
    ): EventFilter;

    CanWithdraw(_depositRef: null, _canWithdraw: null): EventFilter;
  };

  estimate: {
    deposit(
      _depositor: string,
      _depositRef: Arrayish,
      _code: Arrayish,
      _amount: BigNumberish
    ): Promise<BigNumber>;

    withdraw(
      _depositor: string,
      _depositRef: Arrayish,
      _code: Arrayish,
      _amount: BigNumberish
    ): Promise<BigNumber>;

    setCanWithdraw(
      _depositRef: Arrayish,
      _canWithdraw: boolean
    ): Promise<BigNumber>;
  };
}
