/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ExchangerInterface extends Interface {
  functions: {
    renounceOwnership: TypedFunctionDescription<{ encode([]: []): string }>;

    transferOwnership: TypedFunctionDescription<{
      encode([newOwner]: [string]): string;
    }>;

    setComponents: TypedFunctionDescription<{
      encode([_enervatorManager, _depositDB, _forexDB, _buyDB]: [
        string,
        string,
        string,
        string
      ]): string;
    }>;

    deposit: TypedFunctionDescription<{
      encode([_depositor, _depositRef, _code, _amount]: [
        string,
        Arrayish,
        Arrayish,
        BigNumberish
      ]): string;
    }>;

    setCanWithdraw: TypedFunctionDescription<{
      encode([_depositRef, _canWithdraw]: [Arrayish, boolean]): string;
    }>;

    setRate: TypedFunctionDescription<{
      encode([_code, _rate]: [Arrayish, BigNumberish]): string;
    }>;

    buy: TypedFunctionDescription<{
      encode([_buyer, _buyRef, _depositRef, _amountFIAT]: [
        string,
        Arrayish,
        Arrayish,
        BigNumberish
      ]): string;
    }>;

    bought: TypedFunctionDescription<{
      encode([_buyer, _amountEOR, _buyData]: [
        string,
        BigNumberish,
        Arrayish
      ]): string;
    }>;
  };

  events: {
    Bought: TypedEventDescription<{
      encodeTopics([_epochTime, _buyer, _buyRef, _depositRef]: [
        null,
        null,
        null,
        null
      ]): string[];
    }>;

    OwnershipTransferred: TypedEventDescription<{
      encodeTopics([previousOwner, newOwner]: [
        string | null,
        string | null
      ]): string[];
    }>;
  };
}

export class Exchanger extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Exchanger;
  attach(addressOrName: string): Exchanger;
  deployed(): Promise<Exchanger>;

  on(event: EventFilter | string, listener: Listener): Exchanger;
  once(event: EventFilter | string, listener: Listener): Exchanger;
  addListener(eventName: EventFilter | string, listener: Listener): Exchanger;
  removeAllListeners(eventName: EventFilter | string): Exchanger;
  removeListener(eventName: any, listener: Listener): Exchanger;

  interface: ExchangerInterface;

  functions: {
    renounceOwnership(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setComponents(
      _enervatorManager: string,
      _depositDB: string,
      _forexDB: string,
      _buyDB: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    deposit(
      _depositor: string,
      _depositRef: Arrayish,
      _code: Arrayish,
      _amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setCanWithdraw(
      _depositRef: Arrayish,
      _canWithdraw: boolean,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setRate(
      _code: Arrayish,
      _rate: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    buy(
      _buyer: string,
      _buyRef: Arrayish,
      _depositRef: Arrayish,
      _amountFIAT: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    bought(
      _buyer: string,
      _amountEOR: BigNumberish,
      _buyData: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    owner(): Promise<string>;
    isOwner(): Promise<boolean>;
  };

  filters: {
    Bought(
      _epochTime: null,
      _buyer: null,
      _buyRef: null,
      _depositRef: null
    ): EventFilter;

    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;
  };

  estimate: {
    renounceOwnership(): Promise<BigNumber>;

    transferOwnership(newOwner: string): Promise<BigNumber>;

    setComponents(
      _enervatorManager: string,
      _depositDB: string,
      _forexDB: string,
      _buyDB: string
    ): Promise<BigNumber>;

    deposit(
      _depositor: string,
      _depositRef: Arrayish,
      _code: Arrayish,
      _amount: BigNumberish
    ): Promise<BigNumber>;

    setCanWithdraw(
      _depositRef: Arrayish,
      _canWithdraw: boolean
    ): Promise<BigNumber>;

    setRate(_code: Arrayish, _rate: BigNumberish): Promise<BigNumber>;

    buy(
      _buyer: string,
      _buyRef: Arrayish,
      _depositRef: Arrayish,
      _amountFIAT: BigNumberish
    ): Promise<BigNumber>;

    bought(
      _buyer: string,
      _amountEOR: BigNumberish,
      _buyData: Arrayish
    ): Promise<BigNumber>;
  };
}
