/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ForexInterface extends Interface {
  functions: {
    setRate: TypedFunctionDescription<{
      encode([_code, _rate]: [Arrayish, BigNumberish]): string;
    }>;
  };

  events: {};
}

export class Forex extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Forex;
  attach(addressOrName: string): Forex;
  deployed(): Promise<Forex>;

  on(event: EventFilter | string, listener: Listener): Forex;
  once(event: EventFilter | string, listener: Listener): Forex;
  addListener(eventName: EventFilter | string, listener: Listener): Forex;
  removeAllListeners(eventName: EventFilter | string): Forex;
  removeListener(eventName: any, listener: Listener): Forex;

  interface: ForexInterface;

  functions: {
    getRate(_code: Arrayish): Promise<BigNumber>;

    setRate(
      _code: Arrayish,
      _rate: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  filters: {};

  estimate: {
    setRate(_code: Arrayish, _rate: BigNumberish): Promise<BigNumber>;
  };
}
