/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IBuyInterface extends Interface {
  functions: {
    bought: TypedFunctionDescription<{
      encode([_buyer, _buyRef, _depositRef, _amountEOR]: [
        string,
        Arrayish,
        Arrayish,
        BigNumberish
      ]): string;
    }>;
  };

  events: {};
}

export class IBuy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IBuy;
  attach(addressOrName: string): IBuy;
  deployed(): Promise<IBuy>;

  on(event: EventFilter | string, listener: Listener): IBuy;
  once(event: EventFilter | string, listener: Listener): IBuy;
  addListener(eventName: EventFilter | string, listener: Listener): IBuy;
  removeAllListeners(eventName: EventFilter | string): IBuy;
  removeListener(eventName: any, listener: Listener): IBuy;

  interface: IBuyInterface;

  functions: {
    getExists(_x: string): Promise<boolean>;

    getBuys(_index: BigNumberish): Promise<string>;

    getNumBuys(_buyer: string): Promise<BigNumber>;

    getBuyReference(_buyer: string, _index: BigNumberish): Promise<string>;

    getBuyAmount(_buyerRef: Arrayish): Promise<BigNumber>;

    getBuyAddress(_buyerRef: Arrayish): Promise<string>;

    getDepositReference(_buyerRef: Arrayish): Promise<string>;

    getBuy(
      _buyerRef: Arrayish
    ): Promise<{ amount: BigNumber; depositRef: string; account: string }>;

    bought(
      _buyer: string,
      _buyRef: Arrayish,
      _depositRef: Arrayish,
      _amountEOR: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getNumBuyers(): Promise<BigNumber>;
  };

  filters: {};

  estimate: {
    bought(
      _buyer: string,
      _buyRef: Arrayish,
      _depositRef: Arrayish,
      _amountEOR: BigNumberish
    ): Promise<BigNumber>;
  };
}
