/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IERC777RecipientInterface extends Interface {
  functions: {
    tokensReceived: TypedFunctionDescription<{
      encode([operator, from, to, amount, userData, operatorData]: [
        string,
        string,
        string,
        BigNumberish,
        Arrayish,
        Arrayish
      ]): string;
    }>;
  };

  events: {};
}

export class IERC777Recipient extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IERC777Recipient;
  attach(addressOrName: string): IERC777Recipient;
  deployed(): Promise<IERC777Recipient>;

  on(event: EventFilter | string, listener: Listener): IERC777Recipient;
  once(event: EventFilter | string, listener: Listener): IERC777Recipient;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): IERC777Recipient;
  removeAllListeners(eventName: EventFilter | string): IERC777Recipient;
  removeListener(eventName: any, listener: Listener): IERC777Recipient;

  interface: IERC777RecipientInterface;

  functions: {
    tokensReceived(
      operator: string,
      from: string,
      to: string,
      amount: BigNumberish,
      userData: Arrayish,
      operatorData: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  filters: {};

  estimate: {
    tokensReceived(
      operator: string,
      from: string,
      to: string,
      amount: BigNumberish,
      userData: Arrayish,
      operatorData: Arrayish
    ): Promise<BigNumber>;
  };
}
