/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IERC777Sender } from "./IERC777Sender";

export class IERC777SenderFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC777Sender {
    return new Contract(address, _abi, signerOrProvider) as IERC777Sender;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "operator",
        type: "address"
      },
      {
        name: "from",
        type: "address"
      },
      {
        name: "to",
        type: "address"
      },
      {
        name: "amount",
        type: "uint256"
      },
      {
        name: "userData",
        type: "bytes"
      },
      {
        name: "operatorData",
        type: "bytes"
      }
    ],
    name: "tokensToSend",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  }
];
