/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IExchanger } from "./IExchanger";

export class IExchangerFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExchanger {
    return new Contract(address, _abi, signerOrProvider) as IExchanger;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_enervatorManager",
        type: "address"
      },
      {
        name: "_depositDB",
        type: "address"
      },
      {
        name: "_forexDB",
        type: "address"
      },
      {
        name: "_buyDB",
        type: "address"
      }
    ],
    name: "setComponents",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        name: "_depositRef",
        type: "bytes32"
      },
      {
        name: "_canWithdraw",
        type: "bool"
      }
    ],
    name: "setCanWithdraw",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        name: "_code",
        type: "bytes32"
      },
      {
        name: "_rate",
        type: "uint256"
      }
    ],
    name: "setRate",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        name: "_depositor",
        type: "address"
      },
      {
        name: "_depositRef",
        type: "bytes32"
      },
      {
        name: "_code",
        type: "bytes32"
      },
      {
        name: "_amount",
        type: "uint256"
      }
    ],
    name: "deposit",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        components: [
          {
            name: "buyer",
            type: "address"
          },
          {
            name: "buyRef",
            type: "bytes32"
          },
          {
            name: "depositRef",
            type: "bytes32"
          },
          {
            name: "amountWEI",
            type: "uint256"
          }
        ],
        name: "_buyData",
        type: "tuple"
      }
    ],
    name: "buy",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: false,
    inputs: [
      {
        name: "_buyer",
        type: "address"
      },
      {
        name: "_amountWEI",
        type: "uint256"
      },
      {
        name: "_buyData",
        type: "bytes"
      }
    ],
    name: "bought",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  }
];
