/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IForexInterface extends Interface {
  functions: {
    setRate: TypedFunctionDescription<{
      encode([_code, _rate]: [Arrayish, BigNumberish]): string;
    }>;
  };

  events: {};
}

export class IForex extends Contract {
  connect(signerOrProvider: Signer | Provider | string): IForex;
  attach(addressOrName: string): IForex;
  deployed(): Promise<IForex>;

  on(event: EventFilter | string, listener: Listener): IForex;
  once(event: EventFilter | string, listener: Listener): IForex;
  addListener(eventName: EventFilter | string, listener: Listener): IForex;
  removeAllListeners(eventName: EventFilter | string): IForex;
  removeListener(eventName: any, listener: Listener): IForex;

  interface: IForexInterface;

  functions: {
    getRate(_code: Arrayish): Promise<BigNumber>;

    setRate(
      _code: Arrayish,
      _rate: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  filters: {};

  estimate: {
    setRate(_code: Arrayish, _rate: BigNumberish): Promise<BigNumber>;
  };
}
