/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { IForex } from "./IForex";

export class IForexFactory {
  static connect(address: string, signerOrProvider: Signer | Provider): IForex {
    return new Contract(address, _abi, signerOrProvider) as IForex;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_code",
        type: "bytes32"
      },
      {
        name: "_rate",
        type: "int128"
      }
    ],
    name: "setRate",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  },
  {
    constant: true,
    inputs: [
      {
        name: "_code",
        type: "bytes32"
      }
    ],
    name: "getRate",
    outputs: [
      {
        name: "",
        type: "int128"
      }
    ],
    payable: false,
    stateMutability: "view",
    type: "function"
  }
];
